import os

os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_cifar10 --epoch_id 40 --device cuda:0 --advance_attack 1 --method umap --output_dir cifar10_40")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_cifar10 --epoch_id 80 --device cuda:0 --advance_attack 1 --method umap --output_dir cifar10_80")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_cifar10 --epoch_id 120 --device cuda:0 --advance_attack 1 --method umap --output_dir cifar10_120")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_cifar10 --epoch_id 160 --device cuda:0 --advance_attack 1 --method umap --output_dir cifar10_160")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_cifar10 --epoch_id 200 --device cuda:0 --advance_attack 1 --method umap --output_dir cifar10_200")
#
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_mnist --epoch_id 4 --device cuda:0 --advance_attack 1 --method umap --output_dir mnist_4")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_mnist --epoch_id 8 --device cuda:0 --advance_attack 1 --method umap --output_dir mnist_8")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_mnist --epoch_id 12 --device cuda:0 --advance_attack 1 --method umap --output_dir mnist_12")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_mnist --epoch_id 16 --device cuda:0 --advance_attack 1 --method umap --output_dir mnist_16")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_mnist --epoch_id 20 --device cuda:0 --advance_attack 1 --method umap --output_dir mnist_20")
#
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_fmnist --epoch_id 10 --device cuda:0 --advance_attack 1 --method umap --output_dir fmnist_10")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_fmnist --epoch_id 20 --device cuda:0 --advance_attack 1 --method umap --output_dir fmnist_20")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_fmnist --epoch_id 30 --device cuda:0 --advance_attack 1 --method umap --output_dir fmnist_30")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_fmnist --epoch_id 40 --device cuda:0 --advance_attack 1 --method umap --output_dir fmnist_40")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_fmnist --epoch_id 50 --device cuda:0 --advance_attack 1 --method umap --output_dir fmnist_50")

os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_fashionmnist --epoch_id 10 --device cuda:0 --advance_attack 1 --method tsne --output_dir fmnist_10")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_fashionmnist --epoch_id 20 --device cuda:0 --advance_attack 1 --method tsne --output_dir fmnist_20")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_fashionmnist --epoch_id 30 --device cuda:0 --advance_attack 1 --method tsne --output_dir fmnist_30")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_fashionmnist --epoch_id 40 --device cuda:0 --advance_attack 1 --method tsne --output_dir fmnist_40")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_fashionmnist --epoch_id 50 --device cuda:0 --advance_attack 1 --method tsne --output_dir fmnist_50")
#
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_mnist --epoch_id 4 --device cuda:0 --advance_attack 1 --method tsne --output_dir mnist_4")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_mnist --epoch_id 8 --device cuda:0 --advance_attack 1 --method tsne --output_dir mnist_8")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_mnist --epoch_id 12 --device cuda:0 --advance_attack 1 --method tsne --output_dir mnist_12")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_mnist --epoch_id 16 --device cuda:0 --advance_attack 1 --method tsne --output_dir mnist_16")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_mnist --epoch_id 20 --device cuda:0 --advance_attack 1 --method tsne --output_dir mnist_20")
#
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_cifar10 --epoch_id 40 --device cuda:0 --advance_attack 1 --method tsne --output_dir cifar10_40")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_cifar10 --epoch_id 80 --device cuda:0 --advance_attack 1 --method tsne --output_dir cifar10_80")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_cifar10 --epoch_id 120 --device cuda:0 --advance_attack 1 --method tsne --output_dir cifar10_120")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_cifar10 --epoch_id 160 --device cuda:0 --advance_attack 1 --method tsne --output_dir cifar10_160")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_cifar10 --epoch_id 200 --device cuda:0 --advance_attack 1 --method tsne --output_dir cifar10_200")

os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_fmnist --epoch_id 10 --device cuda:0 --advance_attack 1 --method pca --output_dir fmnist_10")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_fmnist --epoch_id 20 --device cuda:0 --advance_attack 1 --method pca --output_dir fmnist_20")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_fmnist --epoch_id 30 --device cuda:0 --advance_attack 1 --method pca --output_dir fmnist_30")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_fmnist --epoch_id 40 --device cuda:0 --advance_attack 1 --method pca --output_dir fmnist_40")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_fmnist --epoch_id 50 --device cuda:0 --advance_attack 1 --method pca --output_dir fmnist_50")

os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_mnist --epoch_id 4 --device cuda:0 --advance_attack 1 --method pca --output_dir mnist_4")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_mnist --epoch_id 8 --device cuda:0 --advance_attack 1 --method pca --output_dir mnist_8")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_mnist --epoch_id 12 --device cuda:0 --advance_attack 1 --method pca --output_dir mnist_12")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_mnist --epoch_id 16 --device cuda:0 --advance_attack 1 --method pca --output_dir mnist_16")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_mnist --epoch_id 20 --device cuda:0 --advance_attack 1 --method pca --output_dir mnist_20")
#
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_cifar10 --epoch_id 40 --device cuda:0 --advance_attack 1 --method pca --output_dir cifar10_40")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_cifar10 --epoch_id 80 --device cuda:0 --advance_attack 1 --method pca --output_dir cifar10_80")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_cifar10 --epoch_id 120 --device cuda:0 --advance_attack 1 --method pca --output_dir cifar10_120")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_cifar10 --epoch_id 160 --device cuda:0 --advance_attack 1 --method pca --output_dir cifar10_160")
os.system("python exp.py --content_path E:\\DVI_exp_data\\resnet18_cifar10 --epoch_id 200 --device cuda:0 --advance_attack 1 --method pca --output_dir cifar10_200")
